#!/usr/bin/env bash
DATADIR=$HOME/.conn
function join_by { 
input=($@)
if [[ ${input[0]} == "-m" ]]; then
local IFS="@"; shift 2; 
sed "s/@/${input[1]}/g" <<< "$*"
else
local IFS="$1"; shift; echo "$*"; 
fi
}
split_by () {
    string=$1
    separator=$2
	result=()
    tmp=${string//"$separator"/$'\2'}
    IFS=$'\2' read -a arr <<< "$tmp"
	num=$((${#arr[@]} - 1))
	if [[ $3 == "-r" ]]; then
	for substr in "${arr[@]}" ; do
		result[$num]="$substr"
		((num--))
    done
	else
	result=(${arr[@]})
	fi
	echo ${result[@]}
}
_conn()
{
	mapfile -t connections < <(jq '. | paths as $path | select(getpath($path) == "connection") | $path | map(select(. != "type")) | join("@")' $DATADIR/connections.json)
	mapfile -t folders < <(jq -r 'paths as $path | select(getpath($path) == "folder" or getpath($path) == "subfolder") | $path |  map(select(. != "type")) | join("@")' $DATADIR/connections.json)
	mapfile -t profiles < <(jq -r 'keys[]' $DATADIR/profiles.json)
  if [ "${#COMP_WORDS[@]}" = "2" ]; then
	  strings="add remove delete edit modify rename show list folder profile help"
	  for i in ${!connections[@]}; do
		  con=$(split_by ${connections[$i]} "@" -r)
		  con="$(join_by "@" $con)"
		  strings="$strings $con"
	  done
	  for i in ${!folders[@]}; do
		  fol=$(split_by ${folders[$i]} "@" -r)
		  fol="$(join_by "@" $fol)"
		  strings="$strings @$fol"
	  done
	  COMPREPLY=($(compgen -W "$strings" "${COMP_WORDS[1]}"))
  fi
  if [ "${#COMP_WORDS[@]}" = "3" ]; then
	  strings=""
	  if [ "${COMP_WORDS[1]}" = "folder" ]; then strings="add remove rename list help"; fi
	  if [ "${COMP_WORDS[1]}" = "profile" ]; then strings="add remove modify show list help"; fi
	  if [[ "${COMP_WORDS[1]}" =~ ^add|rm|remove|del|delete|mod|modify|edit|ren|rename|show$ ]]; then strings="help"; fi
	  if [[ "${COMP_WORDS[1]}" =~ ^rm|remove|del|delete|mod|modify|edit|ren|rename|show$ ]]; then 
		  for i in ${!connections[@]}; do
		  con=$(split_by ${connections[$i]} "@" -r)
		  con="$(join_by "@" $con)"
	      strings="$strings $con"
		  done
	  fi
	  COMPREPLY=($(compgen -W "$strings" "${COMP_WORDS[2]}"))
  fi
  if [ "${#COMP_WORDS[@]}" = "4" ]; then
	  strings=""
	  if [ "${COMP_WORDS[1]}" = "folder" ]; then
		if [[ "${COMP_WORDS[2]}" =~ ^add|rm|remove|del|delete|ren|rename$ ]] ; then strings="help"; fi
		if [[ "${COMP_WORDS[2]}" =~ ^rm|remove|del|delete|ren|rename$ ]] ; then
			for i in ${!folders[@]}; do
			  fol=$(split_by ${folders[$i]} "@" -r)
			  fol="$(join_by "@" $fol)"
			  strings="$strings $fol"
		    done
		fi
	  fi
	  if [ "${COMP_WORDS[1]}" = "profile" ]; then
		if [[ "${COMP_WORDS[2]}" =~ ^add|rm|remove|del|delete|mod|modify|edit|show$ ]] ; then strings="help"; fi
		if [[ "${COMP_WORDS[2]}" =~ ^rm|remove|del|delete|mod|modify|edit|show$ ]] ; then
			for prof in ${profiles[@]}; do
			  strings="$strings $prof"
		    done
		fi
	  fi
	  COMPREPLY=($(compgen -W "$strings" "${COMP_WORDS[3]}"))
  fi
}
complete -o nosort -F _conn conn
