#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/.conn"
[ -d "$DIR" ] || DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/connfiles"
DATADIR=$HOME/.conn
SCRIPT_NAME="$(basename "$0")"
source $DIR/firstrun.sh
if [ ! -f $DATADIR/.osk ]; then firstrun; fi
source $DIR/loadconfig.sh
source $DIR/errors.sh
source $DIR/var.sh
source $DIR/functions.sh
source $DIR/help.sh
source $DIR/adm.sh
source $DIR/folder.sh
source $DIR/profile.sh
source $DIR/connect.sh
if [ $case == "false" ]; then 
opts=()
while [ $# -gt 0 ]; do
	if [[ $1 =~ ^-.*$ ]]; then opts+=("$1"); else
	opts+=("$(echo $1 | tr '[:upper:]' '[:lower:]')"); fi
	shift
done
set -- "${opts[@]}"; fi
declare -A len
len["add"]=2
len["del"]=2
len["mod"]=2
len["list"]=1
len["ren"]=3
len["show"]=2
len["bulk"]=1
len["help"]=1
len["add help"]=2
len["del help"]=2
len["mod help"]=2
len["ren help"]=2
len["show help"]=2
len["bulk help"]=2
len["folder add"]=3
len["folder del"]=3
len["folder ren"]=4
len["folder list"]=2
len["folder add help"]=3
len["folder del help"]=3
len["folder ren help"]=3
len["folder help"]=2
len["folder"]=2
len["profile add"]=3
len["profile del"]=3
len["profile mod"]=3
len["profile list"]=2
len["profile show"]=3
len["profile add help"]=3
len["profile del help"]=3
len["profile mod help"]=3
len["profile show help"]=3
len["profile help"]=2
len["profile"]=2
declare -A max
max["add"]=3
max["del"]=3
max["mod"]=3
max["list"]=0
max["ren"]=3
max["show"]=3
max["bulk"]=0
max["help"]=0
max["add help"]=0
max["del help"]=0
max["mod help"]=0
max["ren help"]=0
max["show help"]=0
max["bulk help"]=0
max["folder add"]=2
max["folder del"]=2
max["folder ren"]=2
max["folder list"]=0
max["folder add help"]=0
max["folder del help"]=0
max["folder ren help"]=0
max["folder help"]=0
max["folder"]=0
max["profile add"]=1
max["profile del"]=1
max["profile mod"]=1
max["profile list"]=0
max["profile show"]=1
max["profile add help"]=0
max["profile del help"]=0
max["profile mod help"]=0
max["profile show help"]=0
max["profile help"]=0
max["profile"]=0
comm=()
and=()
command=()
if [[ $1 =~ $namesif ]]; then
	for args in $@; do
        if [[ "$args" =~ ^(del|delete|rm|remove)$ ]]; then args="del"; fi
        if [[ "$args" =~ ^(mod|modify|edit)$ ]]; then args="mod"; fi
        if [[ "$args" =~ ^(ren|rename)$ ]]; then args="ren"; fi
        if [[ "$args" =~ ^(help|-h|--help)$ ]]; then args="help"; fi
        if [[ "$args" =~ ^(list|ls)$ ]]; then args="list"; fi
        if [[ "${comm[@]}" =~ ^(add|del|mod|ren|show|list|help|bulk)$ ]] && ([ "$args" = "folder" ] || [ "$args" = "profile" ]); then
        comm=("$args" "${comm[@]}")
        command=("$args" "${command[@]}")
        elif [[ "${comm[*]: -1}" =~ ^(add|del|mod|ren|show|list|help|bulk)$ ]] && [ ! "$args" = "help" ]; then and+=("$args"); command+=("$args"); else
		comm+=("$args")
		command+=("$args");	fi
	done
if [ -z "${len[${comm[@]}]}" ]; then invalid 1; fi
if [ "${len[${comm[@]}]}" -gt ${#command[@]} ]; then invalid 2; fi
if [ "${len[${comm[@]}]}" -lt ${#command[@]} ]; then invalid 3; fi
if [[ ${and[0]} =~ [^$validdir] ]] || [[ ${and[1]} =~ [^$validfile] ]] || [[ ${and[0]}  =~ ^@.*$ ]] || [[ ${and[0]} =~ ^.*@$ ]] || [[ ${and[0]} =~ ^.*@@.*$ ]]; then invalid 5; fi
IFS='@' read -ra ADDR <<< ${and[0]}
if [ ${#ADDR[@]} -gt "${max[${comm[@]}]}" ]; then invalid $((${max[${comm[@]}]} + 4)); fi
if [[ ${ADDR[0]} =~ $namesif || ${and[1]} =~ $namesif || ${ADDR[1]} =~ $namesif || ${ADDR[2]} =~ $namesif ]]; then invalid 4 ; fi
if [ "${comm[*]: -1}" = "help" ]; then comm=("${comm[*]: -1}" "$(eval join_by "-" ${comm[@]::${#comm[@]}-1})"); fi
if [[ "${comm[0]}" =~ ^(del|mod|ren|add|show|list)$ ]]; then comm=("adm"  "${comm[@]}"); fi
eval "${comm[@]} ${ADDR[0]} ${and[1]} ${ADDR[2]} ${ADDR[1]}"
exit 0	
fi
if [ $# -gt 4 ] && [[ $1 =~ $namesif ]]; then invalid 3; fi
if [[ $1 == "--allow-uppercase" ]]; then 
	case $2 in
		true)
			sed -i 's/case=.*/case="true"/' $DATADIR/config;;
		false)
			sed -i 's/case=.*/case="false"/' $DATADIR/config;;
		*)
			invalid 8 $2;;
	esac
	exit 0; fi
if [[ $1 == "--keepalive" ]]; then 
	if [[ $2 =~ ^[0-9]+$ ]]; then
		sed -i "s/idletime=.*/idletime=\"$2\"/" $DATADIR/config
	else
		
		invalid 8 "$2, must be a number"
	fi
	exit 0; fi
connect "$@"
