#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DATADIR=$HOME/.conn
SCRIPT_NAME="$(basename "$0")"
source $DIR/.conn/firstrun.sh
if [ ! -f $DATADIR/.osk ]; then firstrun; fi
source $DATADIR/config
source $DIR/.conn/errors.sh
source $DIR/.conn/var.sh
source $DIR/.conn/functions.sh
source $DIR/.conn/help.sh
source $DIR/.conn/adm.sh
source $DIR/.conn/folder.sh
source $DIR/.conn/profile.sh
source $DIR/.conn/connect.sh
if [ $case == "false" ]; then 
opts=()
while [ $# -gt 0 ]; do
	if [[ $1 =~ ^-.*$ ]]; then opts+=("$1"); else
	opts+=("$(echo $1 | tr '[:upper:]' '[:lower:]')"); fi
	shift
done
set -- "${opts[@]}"; fi
if [ $# -le 4 ] && [[ $1 =~ $namesif ]]
then
	case $1 in
		add)
			if [ $# -eq 1 ]
			 then
				invalid 2
			else
			 if [ $# -eq 2 ]
			  then
				case $2 in
					help|-h|--help)
						help add ;;
					$names)
						invalid 4 ;;
					*)
						if [[ ! $2 =~ [^$validdir] ]] && [[ ! $2 =~ ^@.*$ ]] && [[ ! $2 =~ ^.*@$ ]] && [[ ! $2 =~ ^.*@@.*$ ]]; then
							IFS='@' read -ra ADDR <<< $2
							if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif || ${ADDR[2]} =~ $namesif ]]; then invalid 4 ; fi
							if [ ${#ADDR[@]} -gt 3 ]; then
								invalid 7
							else
							if [ ${#ADDR[@]} -eq 1 ]; then
								adm add ${ADDR[0]}
							else 
							if [ ${#ADDR[@]} -eq 2 ]; then
								adm add ${ADDR[0]} ${ADDR[1]}
							else
								adm add ${ADDR[0]} ${ADDR[2]} ${ADDR[1]}
							fi
							fi
							fi
						else
							invalid 5
						fi ;;
				esac
			else
			  if [ $# -ge 3 ]
			   then
				invalid 3
			  fi
			 fi
			fi ;;
        del|delete|rem|remove|rm)
            if [ $# -eq 1 ]
			 then
				invalid 2
			else
			 if [ $# -eq 2 ]
			  then
				case $2 in
					help|-h|--help)
						help del ;;
					$names)
						invalid 4 ;;
					*)
						if [[ ! $2 =~ [^$validdir] ]] && [[ ! $2 =~ ^@.*$ ]] && [[ ! $2 =~ ^.*@$ ]] && [[ ! $2 =~ ^.*@@.*$ ]]; then
							IFS='@' read -ra ADDR <<< $2
							if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif || ${ADDR[2]} =~ $namesif ]]; then invalid 4 ; fi
							if [ ${#ADDR[@]} -gt 3 ]; then
								invalid 7
							else
							if [ ${#ADDR[@]} -eq 1 ]; then
								adm del ${ADDR[0]}
							else 
							if [ ${#ADDR[@]} -eq 2 ]; then
								adm del ${ADDR[0]} ${ADDR[1]}
							else
								adm del ${ADDR[0]} ${ADDR[2]} ${ADDR[1]}
							fi
							fi
							fi
						else
							invalid 5
						fi ;;
				esac
			else
			  if [ $# -ge 3 ]
			   then
				invalid 3
			  fi
			 fi
			fi ;;
		mod|modify|edit)
            if [ $# -eq 1 ]
			 then
				invalid 2
			else
			 if [ $# -eq 2 ]
			  then
				case $2 in
					help|-h|--help)
						help mod ;;
					$names)
						invalid 4 ;;
					*)
						if [[ ! $2 =~ [^$validdir] ]] && [[ ! $2 =~ ^@.*$ ]] && [[ ! $2 =~ ^.*@$ ]] && [[ ! $2 =~ ^.*@@.*$ ]]; then
							IFS='@' read -ra ADDR <<< $2
							if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif || ${ADDR[2]} =~ $namesif ]]; then invalid 4 ; fi
							if [ ${#ADDR[@]} -gt 3 ]; then
								invalid 7
							else
							if [ ${#ADDR[@]} -eq 1 ]; then
								adm mod ${ADDR[0]}
							else 
							if [ ${#ADDR[@]} -eq 2 ]; then
								adm mod ${ADDR[0]} ${ADDR[1]}
							else
								adm mod ${ADDR[0]} ${ADDR[2]} ${ADDR[1]}
							fi
							fi
							fi
						else
							invalid 5
						fi ;;
				esac
			else
			  if [ $# -ge 3 ]
			   then
				invalid 3
			  fi
			 fi
			fi ;;
		ren|rename)
			if [ $# -le 2 ]; then
				case $2 in
				help|-h|--help)
					help ren;;
				*)
					invalid 2;;
				esac
			fi
			if [ $# -ge 4 ]
			 then
				invalid 3 
			fi
			if [ $# -eq 3 ]
			 then
				case $2 in
					help|-h|--help)
						invalid 3 ;;
					$names)
						invalid 4 ;;
					*)
						if [[ ! $2 =~ [^$validdir] ]] && [[ ! $2 =~ ^@.*$ ]] && [[ ! $2 =~ ^.*@$ ]] && [[ ! $2 =~ ^.*@@.*$ ]] &&  [[ ! $3 =~ [^$validfile] ]]; then
						IFS='@' read -ra ADDR <<< $2
						if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif || ${ADDR[2]} =~ $namesif ]]; then invalid 4 ; fi
						if [ ${#ADDR[@]} -gt 3 ]; then
							invalid 7
						fi
						if [ ${#ADDR[@]} -eq 1 ]; then
							case $3 in
								$names)
									invalid 4 ;;
								*)
									adm ren ${ADDR[0]} $3 ;;
							esac
						fi 
						if [ ${#ADDR[@]} -eq 2 ]; then
							case $3 in
								$names)
									invalid 4 ;;
								*)
									adm ren ${ADDR[0]} $3 ${ADDR[1]};;
							esac
						fi
						if [ ${#ADDR[@]} -eq 3 ]; then
							case $3 in
								$names)
									invalid 4 ;;
								*)
									adm ren ${ADDR[0]} $3 ${ADDR[2]} ${ADDR[1]};;
							esac
						fi
						else
							invalid 5
						fi ;;
				esac
			fi;;
		list|ls)
            if [ $# -eq 1 ]
			 then
				adm list
			else
			  if [ $# -ge 2 ]
			   then
				invalid 3
			  fi
			fi ;;
		help|-h|--help)
			help ;;
        folder)
			case $2 in
				""|help|-h|--help)
					help folder ;;
				ls|list)
					if [ $# -eq 2 ]; then
						folder list
					else
						invalid 3
					fi;;
				rename|ren|add|del|delete|rem|remove|rm)
					if [ $# -eq 2 ]
					then
						invalid 2
					fi
					if [ $# -eq 3 ]
					then
						case $2 in
							add)
								case $3 in
									help|-h|--help)
										help folder-add ;;
									$names)
										invalid 4 ;;
									*)
										if [[ ! $3 =~ [^$validdir] ]] && [[ ! $3 =~ ^@.*$ ]] && [[ ! $3 =~ ^.*@$ ]] && [[ ! $3 =~ ^.*@@.*$ ]]; then
										IFS='@' read -ra ADDR <<< $3
										if [ ${#ADDR[@]} -gt 2 ]; then
											invalid 6
										else
										if [ ${#ADDR[@]} -eq 1 ]; then
											folder add ${ADDR[0]}
										else 
										if [ ${#ADDR[@]} -eq 2 ]; then
											if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif ]]; then invalid 4 ; fi
											folder add ${ADDR[0]} ${ADDR[1]} 
										fi
										fi
										fi
										else
											invalid 5
										fi ;;
								esac ;;
							del|delete|rem|remove|rm)
								case $3 in
									help|-h|--help)
										help folder-del ;;
									$names)
										invalid 4 ;;
									*)
										if [[ ! $3 =~ [^$validdir] ]] && [[ ! $3 =~ ^@.*$ ]] && [[ ! $3 =~ ^.*@$ ]] && [[ ! $3 =~ ^.*@@.*$ ]]; then
										IFS='@' read -ra ADDR <<< $3
										if [ ${#ADDR[@]} -gt 2 ]; then
											invalid 6
										else
										if [ ${#ADDR[@]} -eq 1 ]; then
											folder del ${ADDR[0]}
										else 
										if [ ${#ADDR[@]} -eq 2 ]; then
											if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif ]]; then invalid 4 ; fi
											folder del ${ADDR[0]} ${ADDR[1]} 
										fi
										fi
										fi
										else
											invalid 5
										fi ;;
								esac ;;
						ren|rename)
							case $3 in
								help|-h|--help)
									help folder-ren ;;
								*)
									invalid 2 ;;
								list|ls)
									invalid 3;;
							esac;;
					esac
					fi
					if [ $# -eq 4 ]
					then
						case $2 in
							add|del|delete|rem|remove|rm|ls|list)
								invalid 3 ;;
							ren|rename)
								case $3 in
									help|-h|--help)
										invalid 3 ;;
									$names)
										invalid 4 ;;
									*)
										if [[ ! $3 =~ [^$validdir] ]] && [[ ! $3 =~ ^@.*$ ]] && [[ ! $3 =~ ^.*@$ ]] && [[ ! $3 =~ ^.*@@.*$ ]] &&  [[ ! $4 =~ [^$validfile] ]]; then
										IFS='@' read -ra ADDR <<< $3
										if [ ${#ADDR[@]} -gt 2 ]; then
											invalid 6
										else
										if [ ${#ADDR[@]} -eq 1 ]; then
											case $4 in
												$names)
													invalid 4 ;;
												*)
													folder ren ${ADDR[0]} $4 ;;
											esac
										else 
										if [ ${#ADDR[@]} -eq 2 ]; then
											if [[ ${ADDR[0]} =~ $namesif || ${ADDR[1]} =~ $namesif ]]; then invalid 4 ; fi
											case $4 in
												$names)
													invalid 4 ;;
												*)
													folder ren ${ADDR[0]} $4 ${ADDR[1]} ;;
											esac
										fi
										fi
										fi
										else
											invalid 5
										fi ;;
								esac ;;
						esac
						
					fi ;;
				*)
					invalid 1 ;;
			esac
			;;
        profile)
			if [ $# -le 2 ]
			 then
				case $2 in
					""|help|-h|--help)
						help profile ;;
					list|ls)
						profile list;;
					mod|modify|edit|add|del|delete|rem|remove|rm)
						invalid 2 ;;
					*)
						invalid 1 ;;
				esac
			else
			 if [ $# -eq 3 ]
			  then
				case $2 in
					add)
						case $3 in
							help|-h|--help)
								help profile-add ;;
							$names)
								invalid 4 ;;						
							*)
							if [[ ! $3 =~ [^$validfile] ]]; then
								profile add $3
							else
								invalid 5
							fi ;;
						esac ;;
					del|delete|rem|remove|rm)
						case $3 in
							help|-h|--help)
								help profile-del ;;
							$names)
								invalid 4 ;;
							*)
							if [[ ! $3 =~ [^$validfile] ]]; then
								profile del $3
							else
								invalid 5
							fi ;;
						esac ;;
					mod|modify|edit)
						case $3 in
							help|-h|--help)
								help profile-mod ;;
							$names)
								invalid 4 ;;
							*)
							if [[ ! $3 =~ [^$validfile] ]]; then
								profile mod $3
							else
								invalid 5
							fi ;;
						esac ;;
					list|ls)
						invalid 3;;
					help|-h|--help)
						help profile ;;
					*) 
						invalid 1;;
				esac
			 else	
			  if [ $# -eq 4 ]
			  then
				case $2 in
					""|help|-h|--help)
						help profile ;;
					mod|modify|edit|add|del|delete|rem|remove|rm|ls|list)
						invalid 3 ;;
					*)
						invalid 1 ;;
				esac
			  fi
			 fi
			fi ;;
	esac
	exit 1
fi
if [ $# -gt 4 ] && [[ $1 =~ $namesif ]]; then invalid 3; fi
if [[ $1 == "--allow-uppercase" ]]; then 
	case $2 in
		true)
			sed -i 's/case=.*/case="true"/' $DATADIR/config;;
		false)
			sed -i 's/case=.*/case="false"/' $DATADIR/config;;
		*)
			invalid 8 $2;;
	esac
	exit 1; fi
connect "$@"
